# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox"

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 1323, host: 1323

  config.vm.provision "ansible" do |ansible|

    ansible.playbook = "../../Ansible/Automated_Scripts/FactureSoft.yaml"
    ansible.extra_vars = {
                          RunningOn: "0.0.0.0:8000",
                        }
  end

end
